apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-todo
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-todo
  template:
    metadata:
      labels:
        app: mysql-todo
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
          - name: MYSQL_DATABASE
            value: tododb
          - name: MYSQL_USER
            value: todo
          - name: MYSQL_PASSWORD
            value: todopass
          - name: MYSQL_ROOT_PASSWORD
            value: rootpass
        ports:
        - containerPort: 3306
        volumeMounts:
          - name: mysql-data
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          emptyDir: {}
